// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_test.sql

package database

import (
	"context"
)

const insertData = `-- name: InsertData :many
INSERT INTO fivehundred_test (slug, title, contents)
VALUES ($1, $2, $3)
RETURNING title, contents
`

type InsertDataParams struct {
	Slug     string
	Title    string
	Contents string
}

type InsertDataRow struct {
	Title    string
	Contents string
}

func (q *Queries) InsertData(ctx context.Context, arg InsertDataParams) ([]InsertDataRow, error) {
	rows, err := q.db.QueryContext(ctx, insertData, arg.Slug, arg.Title, arg.Contents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertDataRow
	for rows.Next() {
		var i InsertDataRow
		if err := rows.Scan(&i.Title, &i.Contents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
