// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_test.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const insertBookData = `-- name: InsertBookData :exec
INSERT INTO fivehundred (class, title, contents, slug, class_order)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (class, title)
DO UPDATE SET
  contents = EXCLUDED.contents,
  slug = EXCLUDED.slug,
  class_order = EXCLUDED.class_order,
  updated_at = now()
`

type InsertBookDataParams struct {
	Class      sql.NullString
	Title      string
	Contents   string
	Slug       sql.NullString
	ClassOrder sql.NullInt64
}

func (q *Queries) InsertBookData(ctx context.Context, arg InsertBookDataParams) error {
	_, err := q.db.ExecContext(ctx, insertBookData,
		arg.Class,
		arg.Title,
		arg.Contents,
		arg.Slug,
		arg.ClassOrder,
	)
	return err
}

const insertData = `-- name: InsertData :many
INSERT INTO fivehundred (title, contents)
VALUES ($1, $2)
RETURNING title, contents
`

type InsertDataParams struct {
	Title    string
	Contents string
}

type InsertDataRow struct {
	Title    string
	Contents string
}

func (q *Queries) InsertData(ctx context.Context, arg InsertDataParams) ([]InsertDataRow, error) {
	rows, err := q.db.QueryContext(ctx, insertData, arg.Title, arg.Contents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertDataRow
	for rows.Next() {
		var i InsertDataRow
		if err := rows.Scan(&i.Title, &i.Contents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClass = `-- name: UpdateClass :exec
UPDATE fivehundred
SET class=$1,
  updated_at=now()
WHERE slug = ANY($2::text[])
`

type UpdateClassParams struct {
	Class   sql.NullString
	Column2 []string
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) error {
	_, err := q.db.ExecContext(ctx, updateClass, arg.Class, pq.Array(arg.Column2))
	return err
}

const updateSlug = `-- name: UpdateSlug :exec
UPDATE fivehundred 
SET slug=$1,
  updated_at=now()
WHERE title LIKE $2 || '%'
`

type UpdateSlugParams struct {
	Slug    sql.NullString
	Column2 sql.NullString
}

func (q *Queries) UpdateSlug(ctx context.Context, arg UpdateSlugParams) error {
	_, err := q.db.ExecContext(ctx, updateSlug, arg.Slug, arg.Column2)
	return err
}
