// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type FivehundredTest struct {
	ID        int64
	Slug      string
	Title     string
	Contents  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	IsDeleted sql.NullBool
}
