// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Fivehundred struct {
	ID        uuid.UUID
	Class     sql.NullString
	Title     string
	Contents  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	IsDeleted sql.NullBool
}
