// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	InsertData(ctx context.Context, arg InsertDataParams) ([]InsertDataRow, error)
}

var _ Querier = (*Queries)(nil)
